/////////////////////////////////////////////
 // AERC: Resource Compiler. Version: v0.0.4  
 // This is autogenerated, changes are lost! 
 /////////////////////////////////////////////

#ifndef AERC_Resource_h
#define AERC_Resource_h

#ifdef __cplusplus 
extern "C" { 
#endif 

int Resource_Has(const char* _key); 

const char* Resource_GetText(const char* _key); 

#ifdef __cplusplus 
} 
#endif 

#endif // AERC_Resource_h
